# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 864114
  port: 5432


development:
  <<: *default
  adapter: postgresql
  database: DEMO1_development
  template: template0
  username: postgres
  password: 864114

test:
  <<: *default
  adapter: postgresql
  database: DEMO1_test
  username: postgres
  password: 864114

production:
  <<: *default
  adapter: postgresql
  database: DEMO1_production
  username: postgres
  password: <%= ENV['GSD_DATABASE_PASSWORD'] %>